language: node_js
node_js:
  - "iojs"
jobs:
  include:
    - stage : test
    - stage : deploy
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: $HEROKU_KEY
        app: gmc-pi-app
stages:
  - test
  - name: deploy
    if: branch = master